In [1]:
import os 
import pandas as pd
! mkdir -p ~/.kaggle
! mv /path/to/kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

mv: cannot stat '/path/to/kaggle.json': No such file or directory
chmod: cannot access '/home/user/.kaggle/kaggle.json': No such file or directory

In [41]:
accepted_data = pd.read_csv("accepted_2007_to_2018Q4-2.csv")

/tmp/ipykernel_175649/3579317884.py:1: DtypeWarning: Columns (0,19,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  accepted_data = pd.read_csv("accepted_2007_to_2018Q4-2.csv")

In [42]:
print(accepted_data.head())

          id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0  127342995        NaN     5600.0       5600.0           5600.0   36 months
1  127496351        NaN     7500.0       7500.0           7500.0   36 months
2  127581771        NaN    40000.0      40000.0          40000.0   60 months
3  126920792        NaN    10500.0      10500.0          10500.0   36 months
4  127559553        NaN    34400.0      34400.0          34400.0   36 months

   int_rate  installment grade sub_grade  ... hardship_payoff_balance_amount  \
0     19.03       205.36     D        D3  ...                            NaN
1      9.44       240.04     B        B1  ...                            NaN
2     11.99       889.58     B        B5  ...                            NaN
3     21.45       398.02     D        D5  ...                            NaN
4      6.72      1057.78     A        A3  ...                            NaN

  hardship_last_payment_amount disbursement_method  debt_settlement_flag  \
0                          NaN                Cash                     N
1                          NaN                Cash                     N
2                          NaN                Cash                     N
3                          NaN                Cash                     N
4                          NaN                Cash                     N

  debt_settlement_flag_date settlement_status settlement_date  \
0                       NaN               NaN             NaN
1                       NaN               NaN             NaN
2                       NaN               NaN             NaN
3                       NaN               NaN             NaN
4                       NaN               NaN             NaN

  settlement_amount settlement_percentage settlement_term
0               NaN                   NaN             NaN
1               NaN                   NaN             NaN
2               NaN                   NaN             NaN
3               NaN                   NaN             NaN
4               NaN                   NaN             NaN

[5 rows x 151 columns]

In [43]:
accepted_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 576.0+ MB

In [44]:
accepted_data.isnull().sum()

id                            0
member_id                500000
loan_amnt                    10
funded_amnt                  10
funded_amnt_inv              10
                          ...
settlement_status        494483
settlement_date          494483
settlement_amount        494483
settlement_percentage    494483
settlement_term          494483
Length: 151, dtype: int64

In [45]:
new_dataset = accepted_data.drop(columns=['member_id'])

In [46]:

# Calculate the proportion of missing values for each column
missing_proportions = new_dataset.isnull().mean()

# Print the results for each column
for column, missing_proportion in missing_proportions.items():
    print(f"Proportion of missing values in '{column}': {missing_proportion}")

Proportion of missing values in 'id': 0.0
Proportion of missing values in 'loan_amnt': 2e-05
Proportion of missing values in 'funded_amnt': 2e-05
Proportion of missing values in 'funded_amnt_inv': 2e-05
Proportion of missing values in 'term': 2e-05
Proportion of missing values in 'int_rate': 2e-05
Proportion of missing values in 'installment': 2e-05
Proportion of missing values in 'grade': 2e-05
Proportion of missing values in 'sub_grade': 2e-05
Proportion of missing values in 'emp_title': 0.078354
Proportion of missing values in 'emp_length': 0.071664
Proportion of missing values in 'home_ownership': 2e-05
Proportion of missing values in 'annual_inc': 2e-05
Proportion of missing values in 'verification_status': 2e-05
Proportion of missing values in 'issue_d': 2e-05
Proportion of missing values in 'loan_status': 2e-05
Proportion of missing values in 'pymnt_plan': 2e-05
Proportion of missing values in 'url': 2e-05
Proportion of missing values in 'desc': 0.999986
Proportion of missing values in 'purpose': 2e-05
Proportion of missing values in 'title': 0.016338
Proportion of missing values in 'zip_code': 2e-05
Proportion of missing values in 'addr_state': 2e-05
Proportion of missing values in 'dti': 0.00129
Proportion of missing values in 'delinq_2yrs': 2e-05
Proportion of missing values in 'earliest_cr_line': 2e-05
Proportion of missing values in 'fico_range_low': 2e-05
Proportion of missing values in 'fico_range_high': 2e-05
Proportion of missing values in 'inq_last_6mths': 2e-05
Proportion of missing values in 'mths_since_last_delinq': 0.508252
Proportion of missing values in 'mths_since_last_record': 0.839178
Proportion of missing values in 'open_acc': 2e-05
Proportion of missing values in 'pub_rec': 2e-05
Proportion of missing values in 'revol_bal': 2e-05
Proportion of missing values in 'revol_util': 0.000892
Proportion of missing values in 'total_acc': 2e-05
Proportion of missing values in 'initial_list_status': 2e-05
Proportion of missing values in 'out_prncp': 2e-05
Proportion of missing values in 'out_prncp_inv': 2e-05
Proportion of missing values in 'total_pymnt': 2e-05
Proportion of missing values in 'total_pymnt_inv': 2e-05
Proportion of missing values in 'total_rec_prncp': 2e-05
Proportion of missing values in 'total_rec_int': 2e-05
Proportion of missing values in 'total_rec_late_fee': 2e-05
Proportion of missing values in 'recoveries': 2e-05
Proportion of missing values in 'collection_recovery_fee': 2e-05
Proportion of missing values in 'last_pymnt_d': 0.001286
Proportion of missing values in 'last_pymnt_amnt': 2e-05
Proportion of missing values in 'next_pymnt_d': 0.36064
Proportion of missing values in 'last_credit_pull_d': 3.4e-05
Proportion of missing values in 'last_fico_range_high': 2e-05
Proportion of missing values in 'last_fico_range_low': 2e-05
Proportion of missing values in 'collections_12_mths_ex_med': 2e-05
Proportion of missing values in 'mths_since_last_major_derog': 0.737782
Proportion of missing values in 'policy_code': 2e-05
Proportion of missing values in 'application_type': 2e-05
Proportion of missing values in 'annual_inc_joint': 0.910896
Proportion of missing values in 'dti_joint': 0.910896
Proportion of missing values in 'verification_status_joint': 0.915144
Proportion of missing values in 'acc_now_delinq': 2e-05
Proportion of missing values in 'tot_coll_amt': 2e-05
Proportion of missing values in 'tot_cur_bal': 2e-05
Proportion of missing values in 'open_acc_6m': 2e-05
Proportion of missing values in 'open_act_il': 2e-05
Proportion of missing values in 'open_il_12m': 2e-05
Proportion of missing values in 'open_il_24m': 2e-05
Proportion of missing values in 'mths_since_rcnt_il': 0.030406
Proportion of missing values in 'total_bal_il': 2e-05
Proportion of missing values in 'il_util': 0.142694
Proportion of missing values in 'open_rv_12m': 2e-05
Proportion of missing values in 'open_rv_24m': 2e-05
Proportion of missing values in 'max_bal_bc': 2e-05
Proportion of missing values in 'all_util': 0.000164
Proportion of missing values in 'total_rev_hi_lim': 2e-05
Proportion of missing values in 'inq_fi': 2e-05
Proportion of missing values in 'total_cu_tl': 2e-05
Proportion of missing values in 'inq_last_12m': 2e-05
Proportion of missing values in 'acc_open_past_24mths': 2e-05
Proportion of missing values in 'avg_cur_bal': 6.4e-05
Proportion of missing values in 'bc_open_to_buy': 0.0123
Proportion of missing values in 'bc_util': 0.012762
Proportion of missing values in 'chargeoff_within_12_mths': 2e-05
Proportion of missing values in 'delinq_amnt': 2e-05
Proportion of missing values in 'mo_sin_old_il_acct': 0.030406
Proportion of missing values in 'mo_sin_old_rev_tl_op': 2e-05
Proportion of missing values in 'mo_sin_rcnt_rev_tl_op': 2e-05
Proportion of missing values in 'mo_sin_rcnt_tl': 2e-05
Proportion of missing values in 'mort_acc': 2e-05
Proportion of missing values in 'mths_since_recent_bc': 0.011596
Proportion of missing values in 'mths_since_recent_bc_dlq': 0.770894
Proportion of missing values in 'mths_since_recent_inq': 0.115062
Proportion of missing values in 'mths_since_recent_revol_delinq': 0.66843
Proportion of missing values in 'num_accts_ever_120_pd': 2e-05
Proportion of missing values in 'num_actv_bc_tl': 2e-05
Proportion of missing values in 'num_actv_rev_tl': 2e-05
Proportion of missing values in 'num_bc_sats': 2e-05
Proportion of missing values in 'num_bc_tl': 2e-05
Proportion of missing values in 'num_il_tl': 2e-05
Proportion of missing values in 'num_op_rev_tl': 2e-05
Proportion of missing values in 'num_rev_accts': 2e-05
Proportion of missing values in 'num_rev_tl_bal_gt_0': 2e-05
Proportion of missing values in 'num_sats': 2e-05
Proportion of missing values in 'num_tl_120dpd_2m': 0.040914
Proportion of missing values in 'num_tl_30dpd': 2e-05
Proportion of missing values in 'num_tl_90g_dpd_24m': 2e-05
Proportion of missing values in 'num_tl_op_past_12m': 2e-05
Proportion of missing values in 'pct_tl_nvr_dlq': 2.4e-05
Proportion of missing values in 'percent_bc_gt_75': 0.012328
Proportion of missing values in 'pub_rec_bankruptcies': 2e-05
Proportion of missing values in 'tax_liens': 2e-05
Proportion of missing values in 'tot_hi_cred_lim': 2e-05
Proportion of missing values in 'total_bal_ex_mort': 2e-05
Proportion of missing values in 'total_bc_limit': 2e-05
Proportion of missing values in 'total_il_high_credit_limit': 2e-05
Proportion of missing values in 'revol_bal_joint': 0.914572
Proportion of missing values in 'sec_app_fico_range_low': 0.914572
Proportion of missing values in 'sec_app_fico_range_high': 0.914572
Proportion of missing values in 'sec_app_earliest_cr_line': 0.914572
Proportion of missing values in 'sec_app_inq_last_6mths': 0.914572
Proportion of missing values in 'sec_app_mort_acc': 0.914572
Proportion of missing values in 'sec_app_open_acc': 0.914572
Proportion of missing values in 'sec_app_revol_util': 0.9159
Proportion of missing values in 'sec_app_open_act_il': 0.914572
Proportion of missing values in 'sec_app_num_rev_accts': 0.914572
Proportion of missing values in 'sec_app_chargeoff_within_12_mths': 0.914572
Proportion of missing values in 'sec_app_collections_12_mths_ex_med': 0.914572
Proportion of missing values in 'sec_app_mths_since_last_major_derog': 0.971656
Proportion of missing values in 'hardship_flag': 2e-05
Proportion of missing values in 'hardship_type': 0.99418
Proportion of missing values in 'hardship_reason': 0.99418
Proportion of missing values in 'hardship_status': 0.99418
Proportion of missing values in 'deferral_term': 0.99418
Proportion of missing values in 'hardship_amount': 0.99418
Proportion of missing values in 'hardship_start_date': 0.99418
Proportion of missing values in 'hardship_end_date': 0.99418
Proportion of missing values in 'payment_plan_start_date': 0.99418
Proportion of missing values in 'hardship_length': 0.99418
Proportion of missing values in 'hardship_dpd': 0.99418
Proportion of missing values in 'hardship_loan_status': 0.99418
Proportion of missing values in 'orig_projected_additional_accrued_interest': 0.995436
Proportion of missing values in 'hardship_payoff_balance_amount': 0.99418
Proportion of missing values in 'hardship_last_payment_amount': 0.99418
Proportion of missing values in 'disbursement_method': 2e-05
Proportion of missing values in 'debt_settlement_flag': 2e-05
Proportion of missing values in 'debt_settlement_flag_date': 0.988966
Proportion of missing values in 'settlement_status': 0.988966
Proportion of missing values in 'settlement_date': 0.988966
Proportion of missing values in 'settlement_amount': 0.988966
Proportion of missing values in 'settlement_percentage': 0.988966
Proportion of missing values in 'settlement_term': 0.988966

In [47]:
# List of columns with more than 50% missing values
columns_to_drop = missing_proportions[missing_proportions > 0.5].index

# Drop columns from DataFrame
new_dataset.drop(columns=columns_to_drop, inplace=True)

# Display the resulting DataFrame
print("DataFrame after dropping columns:")
print(new_dataset)

DataFrame after dropping columns:
               id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0       127342995     5600.0       5600.0           5600.0   36 months
1       127496351     7500.0       7500.0           7500.0   36 months
2       127581771    40000.0      40000.0          40000.0   60 months
3       126920792    10500.0      10500.0          10500.0   36 months
4       127559553    34400.0      34400.0          34400.0   36 months
...           ...        ...          ...              ...         ...
499995   75333445    35000.0      35000.0          35000.0   36 months
499996   74582703    28000.0      28000.0          28000.0   60 months
499997   75295505    23575.0      23575.0          23575.0   36 months
499998   75144864    20000.0      20000.0          20000.0   60 months
499999   75275669    25000.0      25000.0          25000.0   60 months

        int_rate  installment grade sub_grade                emp_title  ...  \
0          19.03       205.36     D        D3                      NaN  ...
1           9.44       240.04     B        B1               Supervisor  ...
2          11.99       889.58     B        B5     Pharmacist In Charge  ...
3          21.45       398.02     D        D5                      NaN  ...
4           6.72      1057.78     A        A3                 Attorney  ...
...          ...          ...   ...       ...                      ...  ...
499995     10.75      1141.72     B        B4       VP, Internal Audit  ...
499996     20.75       753.57     E        E2  Corporate Sales Manager  ...
499997     20.75       885.17     E        E2               Consultant  ...
499998     19.53       524.67     D        D5                   Driver  ...
499999      8.39       511.59     B        B1                 Security  ...

       percent_bc_gt_75 pub_rec_bankruptcies  tax_liens tot_hi_cred_lim  \
0                  30.0                  0.0        0.0         33800.0
1                  28.6                  0.0        0.0        412488.0
2                   0.0                  0.0        0.0        500197.0
3                  50.0                  0.0        0.0         11200.0
4                   0.0                  0.0        0.0        553320.0
...                 ...                  ...        ...             ...
499995              8.3                  0.0        0.0        732850.0
499996             40.0                  1.0        1.0         34921.0
499997              0.0                  0.0        0.0        103117.0
499998            100.0                  0.0        0.0         25200.0
499999             22.2                  0.0        0.0        231323.0

       total_bal_ex_mort total_bc_limit total_il_high_credit_limit  \
0                13278.0        16500.0                     3000.0
1                96844.0        33800.0                    98530.0
2               252970.0         6000.0                   250147.0
3                 6340.0         7300.0                        0.0
4               118852.0        51400.0                   150920.0
...                  ...            ...                        ...
499995          214295.0       119500.0                   219758.0
499996           14739.0        23700.0                     8000.0
499997           59645.0        22000.0                    63417.0
499998           18903.0         7000.0                    13600.0
499999           61786.0        55500.0                    43814.0

       hardship_flag disbursement_method debt_settlement_flag
0                  N                Cash                    N
1                  N                Cash                    N
2                  N                Cash                    N
3                  N                Cash                    N
4                  N                Cash                    N
...              ...                 ...                  ...
499995             N                Cash                    N
499996             N                Cash                    N
499997             N                Cash                    N
499998             N                Cash                    N
499999             N                Cash                    N

[500000 rows x 108 columns]

In [48]:
#Filling missing values with Mode
for column in new_dataset.columns:
    new_dataset[column].fillna(new_dataset[column].mode()[0], inplace=True)

# Display the resulting DataFrame after imputation
print(new_dataset)

/tmp/ipykernel_175649/341000891.py:3: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  new_dataset[column].fillna(new_dataset[column].mode()[0], inplace=True)
/tmp/ipykernel_175649/341000891.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_dataset[column].fillna(new_dataset[column].mode()[0], inplace=True)

               id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0       127342995     5600.0       5600.0           5600.0   36 months
1       127496351     7500.0       7500.0           7500.0   36 months
2       127581771    40000.0      40000.0          40000.0   60 months
3       126920792    10500.0      10500.0          10500.0   36 months
4       127559553    34400.0      34400.0          34400.0   36 months
...           ...        ...          ...              ...         ...
499995   75333445    35000.0      35000.0          35000.0   36 months
499996   74582703    28000.0      28000.0          28000.0   60 months
499997   75295505    23575.0      23575.0          23575.0   36 months
499998   75144864    20000.0      20000.0          20000.0   60 months
499999   75275669    25000.0      25000.0          25000.0   60 months

        int_rate  installment grade sub_grade                emp_title  ...  \
0          19.03       205.36     D        D3                  Teacher  ...
1           9.44       240.04     B        B1               Supervisor  ...
2          11.99       889.58     B        B5     Pharmacist In Charge  ...
3          21.45       398.02     D        D5                  Teacher  ...
4           6.72      1057.78     A        A3                 Attorney  ...
...          ...          ...   ...       ...                      ...  ...
499995     10.75      1141.72     B        B4       VP, Internal Audit  ...
499996     20.75       753.57     E        E2  Corporate Sales Manager  ...
499997     20.75       885.17     E        E2               Consultant  ...
499998     19.53       524.67     D        D5                   Driver  ...
499999      8.39       511.59     B        B1                 Security  ...

       percent_bc_gt_75 pub_rec_bankruptcies  tax_liens tot_hi_cred_lim  \
0                  30.0                  0.0        0.0         33800.0
1                  28.6                  0.0        0.0        412488.0
2                   0.0                  0.0        0.0        500197.0
3                  50.0                  0.0        0.0         11200.0
4                   0.0                  0.0        0.0        553320.0
...                 ...                  ...        ...             ...
499995              8.3                  0.0        0.0        732850.0
499996             40.0                  1.0        1.0         34921.0
499997              0.0                  0.0        0.0        103117.0
499998            100.0                  0.0        0.0         25200.0
499999             22.2                  0.0        0.0        231323.0

       total_bal_ex_mort total_bc_limit total_il_high_credit_limit  \
0                13278.0        16500.0                     3000.0
1                96844.0        33800.0                    98530.0
2               252970.0         6000.0                   250147.0
3                 6340.0         7300.0                        0.0
4               118852.0        51400.0                   150920.0
...                  ...            ...                        ...
499995          214295.0       119500.0                   219758.0
499996           14739.0        23700.0                     8000.0
499997           59645.0        22000.0                    63417.0
499998           18903.0         7000.0                    13600.0
499999           61786.0        55500.0                    43814.0

       hardship_flag disbursement_method debt_settlement_flag
0                  N                Cash                    N
1                  N                Cash                    N
2                  N                Cash                    N
3                  N                Cash                    N
4                  N                Cash                    N
...              ...                 ...                  ...
499995             N                Cash                    N
499996             N                Cash                    N
499997             N                Cash                    N
499998             N                Cash                    N
499999             N                Cash                    N

[500000 rows x 108 columns]

In [49]:
#Filling missing values with Mode
for column in new_dataset.columns:
    new_dataset[column].fillna(new_dataset[column].mode()[0], inplace=True)

# Display the resulting DataFrame after imputation
print(new_dataset)

/tmp/ipykernel_175649/341000891.py:3: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  new_dataset[column].fillna(new_dataset[column].mode()[0], inplace=True)
/tmp/ipykernel_175649/341000891.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_dataset[column].fillna(new_dataset[column].mode()[0], inplace=True)

               id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0       127342995     5600.0       5600.0           5600.0   36 months
1       127496351     7500.0       7500.0           7500.0   36 months
2       127581771    40000.0      40000.0          40000.0   60 months
3       126920792    10500.0      10500.0          10500.0   36 months
4       127559553    34400.0      34400.0          34400.0   36 months
...           ...        ...          ...              ...         ...
499995   75333445    35000.0      35000.0          35000.0   36 months
499996   74582703    28000.0      28000.0          28000.0   60 months
499997   75295505    23575.0      23575.0          23575.0   36 months
499998   75144864    20000.0      20000.0          20000.0   60 months
499999   75275669    25000.0      25000.0          25000.0   60 months

        int_rate  installment grade sub_grade                emp_title  ...  \
0          19.03       205.36     D        D3                  Teacher  ...
1           9.44       240.04     B        B1               Supervisor  ...
2          11.99       889.58     B        B5     Pharmacist In Charge  ...
3          21.45       398.02     D        D5                  Teacher  ...
4           6.72      1057.78     A        A3                 Attorney  ...
...          ...          ...   ...       ...                      ...  ...
499995     10.75      1141.72     B        B4       VP, Internal Audit  ...
499996     20.75       753.57     E        E2  Corporate Sales Manager  ...
499997     20.75       885.17     E        E2               Consultant  ...
499998     19.53       524.67     D        D5                   Driver  ...
499999      8.39       511.59     B        B1                 Security  ...

       percent_bc_gt_75 pub_rec_bankruptcies  tax_liens tot_hi_cred_lim  \
0                  30.0                  0.0        0.0         33800.0
1                  28.6                  0.0        0.0        412488.0
2                   0.0                  0.0        0.0        500197.0
3                  50.0                  0.0        0.0         11200.0
4                   0.0                  0.0        0.0        553320.0
...                 ...                  ...        ...             ...
499995              8.3                  0.0        0.0        732850.0
499996             40.0                  1.0        1.0         34921.0
499997              0.0                  0.0        0.0        103117.0
499998            100.0                  0.0        0.0         25200.0
499999             22.2                  0.0        0.0        231323.0

       total_bal_ex_mort total_bc_limit total_il_high_credit_limit  \
0                13278.0        16500.0                     3000.0
1                96844.0        33800.0                    98530.0
2               252970.0         6000.0                   250147.0
3                 6340.0         7300.0                        0.0
4               118852.0        51400.0                   150920.0
...                  ...            ...                        ...
499995          214295.0       119500.0                   219758.0
499996           14739.0        23700.0                     8000.0
499997           59645.0        22000.0                    63417.0
499998           18903.0         7000.0                    13600.0
499999           61786.0        55500.0                    43814.0

       hardship_flag disbursement_method debt_settlement_flag
0                  N                Cash                    N
1                  N                Cash                    N
2                  N                Cash                    N
3                  N                Cash                    N
4                  N                Cash                    N
...              ...                 ...                  ...
499995             N                Cash                    N
499996             N                Cash                    N
499997             N                Cash                    N
499998             N                Cash                    N
499999             N                Cash                    N

[500000 rows x 108 columns]

In [50]:
new_dataset.shape

(500000, 108)

In [52]:
new_dataset['loan_status'].value_counts()

loan_status
Current               307752
Fully Paid            137945
Charged Off            42365
Late (31-120 days)      7498
In Grace Period         2951
Late (16-30 days)       1473
Default                   16
Name: count, dtype: int64

In [53]:

# Drop rows where 'Current' appears in the 'loan status' column
new_dataset = new_dataset[new_dataset['loan_status'] != 'Current']

# Display the modified DataFrame
print(new_dataset)

               id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
2       127581771    40000.0      40000.0          40000.0   60 months
8       127388898    25000.0      25000.0          25000.0   60 months
13      127410532     1600.0       1600.0           1600.0   36 months
14      127148405    30000.0      30000.0          30000.0   36 months
17      127184720    28975.0      28975.0          28975.0   36 months
...           ...        ...          ...              ...         ...
499994   75333719    25000.0      25000.0          24900.0   36 months
499996   74582703    28000.0      28000.0          28000.0   60 months
499997   75295505    23575.0      23575.0          23575.0   36 months
499998   75144864    20000.0      20000.0          20000.0   60 months
499999   75275669    25000.0      25000.0          25000.0   60 months

        int_rate  installment grade sub_grade                emp_title  ...  \
2          11.99       889.58     B        B5     Pharmacist In Charge  ...
8          18.06       635.66     D        D2           Director of HR  ...
13         12.62        53.62     C        C1                 Security  ...
14          9.93       967.03     B        B2                    owner  ...
17         16.02      1018.97     C        C5            HR Supervisor  ...
...          ...          ...   ...       ...                      ...  ...
499994     13.67       850.44     C        C3                      ceo  ...
499996     20.75       753.57     E        E2  Corporate Sales Manager  ...
499997     20.75       885.17     E        E2               Consultant  ...
499998     19.53       524.67     D        D5                   Driver  ...
499999      8.39       511.59     B        B1                 Security  ...

       percent_bc_gt_75 pub_rec_bankruptcies  tax_liens tot_hi_cred_lim  \
2                   0.0                  0.0        0.0        500197.0
8                 100.0                  0.0        0.0        360280.0
13                 33.3                  0.0        0.0          2400.0
14                 42.9                  0.0        0.0        226249.0
17                 28.6                  0.0        0.0        192783.0
...                 ...                  ...        ...             ...
499994              0.0                  0.0        1.0        108999.0
499996             40.0                  1.0        1.0         34921.0
499997              0.0                  0.0        0.0        103117.0
499998            100.0                  0.0        0.0         25200.0
499999             22.2                  0.0        0.0        231323.0

       total_bal_ex_mort total_bc_limit total_il_high_credit_limit  \
2               252970.0         6000.0                   250147.0
8                31674.0        14500.0                    54780.0
13                1069.0         2400.0                        0.0
14               42963.0        41500.0                    24349.0
17               64079.0        22500.0                   101633.0
...                  ...            ...                        ...
499994           47842.0        22300.0                    84899.0
499996           14739.0        23700.0                     8000.0
499997           59645.0        22000.0                    63417.0
499998           18903.0         7000.0                    13600.0
499999           61786.0        55500.0                    43814.0

       hardship_flag disbursement_method debt_settlement_flag
2                  N                Cash                    N
8                  N                Cash                    N
13                 N                Cash                    N
14                 N                Cash                    N
17                 N                Cash                    N
...              ...                 ...                  ...
499994             N                Cash                    N
499996             N                Cash                    N
499997             N                Cash                    N
499998             N                Cash                    N
499999             N                Cash                    N

[192248 rows x 108 columns]

In [54]:
new_dataset['loan_status'].value_counts()

loan_status
Fully Paid            137945
Charged Off            42365
Late (31-120 days)      7498
In Grace Period         2951
Late (16-30 days)       1473
Default                   16
Name: count, dtype: int64

In [55]:
new_dataset['loan_status'].replace('Fully Paid', 'Good', inplace=True)

/tmp/ipykernel_175649/740377838.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_dataset['loan_status'].replace('Fully Paid', 'Good', inplace=True)

In [56]:
new_dataset['loan_status'].value_counts()

loan_status
Good                  137945
Charged Off            42365
Late (31-120 days)      7498
In Grace Period         2951
Late (16-30 days)       1473
Default                   16
Name: count, dtype: int64

In [57]:
new_dataset['loan_status'].replace('Charged Off', 'Bad', inplace=True)

/tmp/ipykernel_175649/3895158894.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_dataset['loan_status'].replace('Charged Off', 'Bad', inplace=True)

In [58]:
new_dataset['loan_status'].value_counts()

loan_status
Good                  137945
Bad                    42365
Late (31-120 days)      7498
In Grace Period         2951
Late (16-30 days)       1473
Default                   16
Name: count, dtype: int64

In [59]:
# Categories to be replaced with 'bad'
categories_to_merge = ['Default']

# Replace specified categories with 'bad'
new_dataset['loan_status'] = new_dataset['loan_status'].replace(categories_to_merge, 'Bad')

# Display the modified DataFrame
print(new_dataset)

               id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
2       127581771    40000.0      40000.0          40000.0   60 months
8       127388898    25000.0      25000.0          25000.0   60 months
13      127410532     1600.0       1600.0           1600.0   36 months
14      127148405    30000.0      30000.0          30000.0   36 months
17      127184720    28975.0      28975.0          28975.0   36 months
...           ...        ...          ...              ...         ...
499994   75333719    25000.0      25000.0          24900.0   36 months
499996   74582703    28000.0      28000.0          28000.0   60 months
499997   75295505    23575.0      23575.0          23575.0   36 months
499998   75144864    20000.0      20000.0          20000.0   60 months
499999   75275669    25000.0      25000.0          25000.0   60 months

        int_rate  installment grade sub_grade                emp_title  ...  \
2          11.99       889.58     B        B5     Pharmacist In Charge  ...
8          18.06       635.66     D        D2           Director of HR  ...
13         12.62        53.62     C        C1                 Security  ...
14          9.93       967.03     B        B2                    owner  ...
17         16.02      1018.97     C        C5            HR Supervisor  ...
...          ...          ...   ...       ...                      ...  ...
499994     13.67       850.44     C        C3                      ceo  ...
499996     20.75       753.57     E        E2  Corporate Sales Manager  ...
499997     20.75       885.17     E        E2               Consultant  ...
499998     19.53       524.67     D        D5                   Driver  ...
499999      8.39       511.59     B        B1                 Security  ...

       percent_bc_gt_75 pub_rec_bankruptcies  tax_liens tot_hi_cred_lim  \
2                   0.0                  0.0        0.0        500197.0
8                 100.0                  0.0        0.0        360280.0
13                 33.3                  0.0        0.0          2400.0
14                 42.9                  0.0        0.0        226249.0
17                 28.6                  0.0        0.0        192783.0
...                 ...                  ...        ...             ...
499994              0.0                  0.0        1.0        108999.0
499996             40.0                  1.0        1.0         34921.0
499997              0.0                  0.0        0.0        103117.0
499998            100.0                  0.0        0.0         25200.0
499999             22.2                  0.0        0.0        231323.0

       total_bal_ex_mort total_bc_limit total_il_high_credit_limit  \
2               252970.0         6000.0                   250147.0
8                31674.0        14500.0                    54780.0
13                1069.0         2400.0                        0.0
14               42963.0        41500.0                    24349.0
17               64079.0        22500.0                   101633.0
...                  ...            ...                        ...
499994           47842.0        22300.0                    84899.0
499996           14739.0        23700.0                     8000.0
499997           59645.0        22000.0                    63417.0
499998           18903.0         7000.0                    13600.0
499999           61786.0        55500.0                    43814.0

       hardship_flag disbursement_method debt_settlement_flag
2                  N                Cash                    N
8                  N                Cash                    N
13                 N                Cash                    N
14                 N                Cash                    N
17                 N                Cash                    N
...              ...                 ...                  ...
499994             N                Cash                    N
499996             N                Cash                    N
499997             N                Cash                    N
499998             N                Cash                    N
499999             N                Cash                    N

[192248 rows x 108 columns]

In [60]:
new_dataset['loan_status'].value_counts()

loan_status
Good                  137945
Bad                    42381
Late (31-120 days)      7498
In Grace Period         2951
Late (16-30 days)       1473
Name: count, dtype: int64

In [61]:
# Categories to be replaced with 'bad'
categories_to_merge = ['Late (31-120 days)']

# Replace specified categories with 'bad'
new_dataset['loan_status'] = new_dataset['loan_status'].replace(categories_to_merge, 'Bad')

In [62]:
# Categories to be replaced with 'bad'
categories_to_merge = ['Late (31-120 days)']

# Replace specified categories with 'bad'
new_dataset['loan_status'] = new_dataset['loan_status'].replace(categories_to_merge, 'Bad')

In [63]:
# Categories to be replaced with 'bad'
categories_to_merge = ['Late (16-30 days)']

# Replace specified categories with 'bad'
new_dataset['loan_status'] = new_dataset['loan_status'].replace(categories_to_merge, 'Bad')

In [65]:
# Categories to be replaced with 'bad'
categories_to_merge = ['In Grace Period']

# Replace specified categories with 'bad'
new_dataset['loan_status'] = new_dataset['loan_status'].replace(categories_to_merge, 'Bad')

In [66]:
new_dataset['loan_status'].value_counts()

loan_status
Good    137945
Bad      54303
Name: count, dtype: int64

In [67]:
# separating the data for analysis
GOOD = new_dataset[new_dataset.loan_status == 'Good']
BAD = new_dataset[new_dataset.loan_status == 'Bad']

In [68]:
print(GOOD.shape)
print(BAD.shape)

(137945, 108)
(54303, 108)

In [ ]:
UNDERSAMPLING

In [69]:
legit_sample= GOOD.sample(n=54303)

In [70]:
print(legit_sample.shape)
print(BAD.shape)

(54303, 108)
(54303, 108)

In [71]:
new_dataset = pd.concat([legit_sample, BAD], axis=0)

In [72]:
new_dataset.head()

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
228080,77151521,6500.0,6500.0,6500.0,36 months,7.89,203.36,A,A5,Nurse,...,50.0,0.0,0.0,336623.0,22148.0,6200.0,47421.0,N,Cash,N
92843,115413821,2000.0,2000.0,2000.0,36 months,9.44,64.01,B,B1,Nurse,...,0.0,0.0,0.0,87560.0,36958.0,33300.0,41160.0,N,Cash,N
168585,81180338,29000.0,29000.0,29000.0,60 months,14.46,681.72,C,C4,Marine Superintendent,...,100.0,0.0,0.0,31753.0,18023.0,3100.0,23653.0,N,Cash,N
481553,102374969,15000.0,15000.0,15000.0,60 months,13.99,348.95,C,C3,Business Support Analyst,...,16.7,0.0,0.0,99529.0,39483.0,29700.0,50929.0,N,Cash,N
215556,77379249,20000.0,20000.0,20000.0,60 months,9.75,422.49,B,B3,Data Analyst & Exec Admin Asst,...,100.0,1.0,0.0,423218.0,115383.0,28000.0,98528.0,N,Cash,N

In [73]:
# Convert all columns to string type (object) if they contain categorical values
new_dataset = new_dataset.apply(lambda x: x.astype(str) if x.dtype == 'object' else x)

# Print the updated DataFrame to verify
print("DataFrame after converting categorical columns to strings:")
print(new_dataset)

DataFrame after converting categorical columns to strings:
               id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
228080   77151521     6500.0       6500.0           6500.0   36 months
92843   115413821     2000.0       2000.0           2000.0   36 months
168585   81180338    29000.0      29000.0          29000.0   60 months
481553  102374969    15000.0      15000.0          15000.0   60 months
215556   77379249    20000.0      20000.0          20000.0   60 months
...           ...        ...          ...              ...         ...
499987   75301285     6025.0       6025.0           6025.0   36 months
499988   75191512     9600.0       9600.0           9600.0   36 months
499996   74582703    28000.0      28000.0          28000.0   60 months
499998   75144864    20000.0      20000.0          20000.0   60 months
499999   75275669    25000.0      25000.0          25000.0   60 months

        int_rate  installment grade sub_grade                       emp_title  \
228080      7.89       203.36     A        A5                           Nurse
92843       9.44        64.01     B        B1                           Nurse
168585     14.46       681.72     C        C4          Marine Superintendent
481553     13.99       348.95     C        C3       Business Support Analyst
215556      9.75       422.49     B        B3  Data Analyst & Exec Admin Asst
...          ...          ...   ...       ...                             ...
499987     10.75       196.54     B        B4                         Manager
499988      9.75       308.64     B        B3                  Branch Manager
499996     20.75       753.57     E        E2         Corporate Sales Manager
499998     19.53       524.67     D        D5                          Driver
499999      8.39       511.59     B        B1                        Security

        ... percent_bc_gt_75 pub_rec_bankruptcies  tax_liens tot_hi_cred_lim  \
228080  ...             50.0                  0.0        0.0        336623.0
92843   ...              0.0                  0.0        0.0         87560.0
168585  ...            100.0                  0.0        0.0         31753.0
481553  ...             16.7                  0.0        0.0         99529.0
215556  ...            100.0                  1.0        0.0        423218.0
...     ...              ...                  ...        ...             ...
499987  ...              0.0                  0.0        0.0         12300.0
499988  ...             66.7                  0.0        0.0         19139.0
499996  ...             40.0                  1.0        1.0         34921.0
499998  ...            100.0                  0.0        0.0         25200.0
499999  ...             22.2                  0.0        0.0        231323.0

       total_bal_ex_mort total_bc_limit total_il_high_credit_limit  \
228080           22148.0         6200.0                    47421.0
92843            36958.0        33300.0                    41160.0
168585           18023.0         3100.0                    23653.0
481553           39483.0        29700.0                    50929.0
215556          115383.0        28000.0                    98528.0
...                  ...            ...                        ...
499987            3066.0         9300.0                        0.0
499988           13720.0        10700.0                     5239.0
499996           14739.0        23700.0                     8000.0
499998           18903.0         7000.0                    13600.0
499999           61786.0        55500.0                    43814.0

       hardship_flag disbursement_method debt_settlement_flag
228080             N                Cash                    N
92843              N                Cash                    N
168585             N                Cash                    N
481553             N                Cash                    N
215556             N                Cash                    N
...              ...                 ...                  ...
499987             N                Cash                    N
499988             N                Cash                    N
499996             N                Cash                    N
499998             N                Cash                    N
499999             N                Cash                    N

[108606 rows x 108 columns]

In [80]:
# Initialize LabelEncoder
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

# Iterate through each column
for col in new_dataset.columns:
    if new_dataset[col].dtype == 'object' and col != 'loan_status':  # Check if the column is categorical and not 'loan_status'
        new_dataset[col + '_encoded'] = label_encoder.fit_transform(new_dataset[col])
        new_dataset.drop(columns=[col], inplace=True)  # Drop the original categorical column after encoding

# Print encoded columns
encoded_columns = [col for col in new_dataset.columns if '_encoded' in col]
print("\nEncoded Columns:")
print(new_dataset[encoded_columns])

# Identify columns that are of type 'object' and exclude 'loan_status'
columns_to_drop = [col for col in new_dataset.select_dtypes(include='object').columns if col != 'loan_status']

# Drop identified columns
new_dataset.drop(columns=columns_to_drop, inplace=True)

# Print the updated DataFrame
print("\nDataFrame after Label Encoding and dropping original categorical columns:")
print(new_dataset)

Encoded Columns:
        id_encoded  term_encoded  grade_encoded  sub_grade_encoded  \
228080       82619             0              0                  4
92843        40203             0              1                  5
168585      101619             1              2                 13
481553         205             1              2                 12
215556       84940             1              1                  7
...            ...           ...            ...                ...
499987       69415             0              1                  8
499988       68415             0              1                  7
499996       66518             1              4                 21
499998       68006             1              3                 19
499999       69183             1              1                  5

        emp_title_encoded  emp_length_encoded  home_ownership_encoded  \
228080              20347                   5                       1
92843               20347                   5                       3
168585              18787                   5                       3
481553               3972                   4                       1
215556               8128                   3                       1
...                   ...                 ...                     ...
499987              18361                   9                       3
499988               3542                   1                       1
499996               7208                   5                       2
499998              10113                   1                       3
499999              27468                   2                       1

        verification_status_encoded  issue_d_encoded  pymnt_plan_encoded  ...  \
228080                            0                0                   0  ...
92843                             2                2                   0  ...
168585                            1                8                   0  ...
481553                            0                1                   0  ...
215556                            0               11                   0  ...
...                             ...              ...                 ...  ...
499987                            0               10                   0  ...
499988                            1               10                   0  ...
499996                            1               10                   0  ...
499998                            0               10                   0  ...
499999                            0               10                   0  ...

        addr_state_encoded  earliest_cr_line_encoded  \
228080                   9                       519
92843                    4                       151
168585                  30                       522
481553                  41                       568
215556                   5                       312
...                    ...                       ...
499987                  18                       576
499988                  41                        90
499996                  21                       513
499998                  33                       621
499999                  16                       188

        initial_list_status_encoded  last_pymnt_d_encoded  \
228080                            1                    14
92843                             1                     7
168585                            1                     8
481553                            1                    26
215556                            1                    24
...                             ...                   ...
499987                            1                    33
499988                            1                    11
499996                            1                     3
499998                            1                    20
499999                            1                     8

        next_pymnt_d_encoded  last_credit_pull_d_encoded  \
228080                     0                          11
92843                      0                          24
168585                     0                           8
481553                     0                          24
215556                     0                          27
...                      ...                         ...
499987                     0                           9
499988                     0                          24
499996                     0                          24
499998                     0                          24
499999                     0                          24

        application_type_encoded  hardship_flag_encoded  \
228080                         0                      0
92843                          0                      0
168585                         0                      0
481553                         0                      0
215556                         0                      0
...                          ...                    ...
499987                         0                      0
499988                         0                      0
499996                         0                      0
499998                         0                      0
499999                         0                      0

        disbursement_method_encoded  debt_settlement_flag_encoded
228080                            0                             0
92843                             0                             0
168585                            0                             0
481553                            0                             0
215556                            0                             0
...                             ...                           ...
499987                            0                             0
499988                            0                             0
499996                            0                             0
499998                            0                             0
499999                            0                             0

[108606 rows x 24 columns]

DataFrame after Label Encoding and dropping original categorical columns:
        loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  \
228080     6500.0       6500.0           6500.0      7.89       203.36
92843      2000.0       2000.0           2000.0      9.44        64.01
168585    29000.0      29000.0          29000.0     14.46       681.72
481553    15000.0      15000.0          15000.0     13.99       348.95
215556    20000.0      20000.0          20000.0      9.75       422.49
...           ...          ...              ...       ...          ...
499987     6025.0       6025.0           6025.0     10.75       196.54
499988     9600.0       9600.0           9600.0      9.75       308.64
499996    28000.0      28000.0          28000.0     20.75       753.57
499998    20000.0      20000.0          20000.0     19.53       524.67
499999    25000.0      25000.0          25000.0      8.39       511.59

        annual_inc loan_status    dti  delinq_2yrs  fico_range_low  ...  \
228080     55000.0        Good  27.32          2.0           695.0  ...
92843      52000.0        Good  20.89          0.0           710.0  ...
168585     65000.0        Good  13.52          0.0           710.0  ...
481553     70000.0        Good  21.96          1.0           705.0  ...
215556    185000.0        Good  11.84          0.0           685.0  ...
...            ...         ...    ...          ...             ...  ...
499987     50000.0         Bad   2.66          0.0           670.0  ...
499988     52000.0         Bad  15.23          0.0           680.0  ...
499996    120000.0         Bad   5.21          0.0           660.0  ...
499998     65000.0         Bad  10.47          0.0           705.0  ...
499999     65000.0         Bad  27.07          0.0           720.0  ...

        addr_state_encoded  earliest_cr_line_encoded  \
228080                   9                       519
92843                    4                       151
168585                  30                       522
481553                  41                       568
215556                   5                       312
...                    ...                       ...
499987                  18                       576
499988                  41                        90
499996                  21                       513
499998                  33                       621
499999                  16                       188

        initial_list_status_encoded  last_pymnt_d_encoded  \
228080                            1                    14
92843                             1                     7
168585                            1                     8
481553                            1                    26
215556                            1                    24
...                             ...                   ...
499987                            1                    33
499988                            1                    11
499996                            1                     3
499998                            1                    20
499999                            1                     8

        next_pymnt_d_encoded  last_credit_pull_d_encoded  \
228080                     0                          11
92843                      0                          24
168585                     0                           8
481553                     0                          24
215556                     0                          27
...                      ...                         ...
499987                     0                           9
499988                     0                          24
499996                     0                          24
499998                     0                          24
499999                     0                          24

        application_type_encoded  hardship_flag_encoded  \
228080                         0                      0
92843                          0                      0
168585                         0                      0
481553                         0                      0
215556                         0                      0
...                          ...                    ...
499987                         0                      0
499988                         0                      0
499996                         0                      0
499998                         0                      0
499999                         0                      0

        disbursement_method_encoded  debt_settlement_flag_encoded
228080                            0                             0
92843                             0                             0
168585                            0                             0
481553                            0                             0
215556                            0                             0
...                             ...                           ...
499987                            0                             0
499988                            0                             0
499996                            0                             0
499998                            0                             0
499999                            0                             0

[108606 rows x 108 columns]

In [81]:
# Assuming 'loan_status' is the column you want to print
new_dataset['loan_status'].value_counts()

loan_status
Good    54303
Bad     54303
Name: count, dtype: int64

In [82]:
print(new_dataset)

        loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  \
228080     6500.0       6500.0           6500.0      7.89       203.36
92843      2000.0       2000.0           2000.0      9.44        64.01
168585    29000.0      29000.0          29000.0     14.46       681.72
481553    15000.0      15000.0          15000.0     13.99       348.95
215556    20000.0      20000.0          20000.0      9.75       422.49
...           ...          ...              ...       ...          ...
499987     6025.0       6025.0           6025.0     10.75       196.54
499988     9600.0       9600.0           9600.0      9.75       308.64
499996    28000.0      28000.0          28000.0     20.75       753.57
499998    20000.0      20000.0          20000.0     19.53       524.67
499999    25000.0      25000.0          25000.0      8.39       511.59

        annual_inc loan_status    dti  delinq_2yrs  fico_range_low  ...  \
228080     55000.0        Good  27.32          2.0           695.0  ...
92843      52000.0        Good  20.89          0.0           710.0  ...
168585     65000.0        Good  13.52          0.0           710.0  ...
481553     70000.0        Good  21.96          1.0           705.0  ...
215556    185000.0        Good  11.84          0.0           685.0  ...
...            ...         ...    ...          ...             ...  ...
499987     50000.0         Bad   2.66          0.0           670.0  ...
499988     52000.0         Bad  15.23          0.0           680.0  ...
499996    120000.0         Bad   5.21          0.0           660.0  ...
499998     65000.0         Bad  10.47          0.0           705.0  ...
499999     65000.0         Bad  27.07          0.0           720.0  ...

        addr_state_encoded  earliest_cr_line_encoded  \
228080                   9                       519
92843                    4                       151
168585                  30                       522
481553                  41                       568
215556                   5                       312
...                    ...                       ...
499987                  18                       576
499988                  41                        90
499996                  21                       513
499998                  33                       621
499999                  16                       188

        initial_list_status_encoded  last_pymnt_d_encoded  \
228080                            1                    14
92843                             1                     7
168585                            1                     8
481553                            1                    26
215556                            1                    24
...                             ...                   ...
499987                            1                    33
499988                            1                    11
499996                            1                     3
499998                            1                    20
499999                            1                     8

        next_pymnt_d_encoded  last_credit_pull_d_encoded  \
228080                     0                          11
92843                      0                          24
168585                     0                           8
481553                     0                          24
215556                     0                          27
...                      ...                         ...
499987                     0                           9
499988                     0                          24
499996                     0                          24
499998                     0                          24
499999                     0                          24

        application_type_encoded  hardship_flag_encoded  \
228080                         0                      0
92843                          0                      0
168585                         0                      0
481553                         0                      0
215556                         0                      0
...                          ...                    ...
499987                         0                      0
499988                         0                      0
499996                         0                      0
499998                         0                      0
499999                         0                      0

        disbursement_method_encoded  debt_settlement_flag_encoded
228080                            0                             0
92843                             0                             0
168585                            0                             0
481553                            0                             0
215556                            0                             0
...                             ...                           ...
499987                            0                             0
499988                            0                             0
499996                            0                             0
499998                            0                             0
499999                            0                             0

[108606 rows x 108 columns]

In [83]:
new_dataset.shape

(108606, 108)

In [84]:
new_dataset.groupby('loan_status').mean()

,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,...,addr_state_encoded,earliest_cr_line_encoded,initial_list_status_encoded,last_pymnt_d_encoded,next_pymnt_d_encoded,last_credit_pull_d_encoded,application_type_encoded,hardship_flag_encoded,disbursement_method_encoded,debt_settlement_flag_encoded
loan_status,,,,,,,,,,,,,,,,,,,,,
Bad,15696.140176,15696.140176,15691.445129,15.982048,482.901574,72593.888235,20.665607,0.378009,689.537687,693.537760,...,22.300978,342.157045,0.745723,18.220301,0.00011,20.976889,0.073569,0.005009,0.014677,0.101449
Good,13996.937554,13996.937554,13992.480618,12.702131,428.394789,80082.940803,18.264619,0.319964,701.181887,705.182053,...,22.406497,340.819292,0.780933,18.093660,0.00000,20.363700,0.052723,0.000000,0.013075,0.000000

In [85]:
X = new_dataset.drop(columns='loan_status', axis=1)
Y = new_dataset['loan_status']

In [86]:
print(X)

        loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  \
228080     6500.0       6500.0           6500.0      7.89       203.36
92843      2000.0       2000.0           2000.0      9.44        64.01
168585    29000.0      29000.0          29000.0     14.46       681.72
481553    15000.0      15000.0          15000.0     13.99       348.95
215556    20000.0      20000.0          20000.0      9.75       422.49
...           ...          ...              ...       ...          ...
499987     6025.0       6025.0           6025.0     10.75       196.54
499988     9600.0       9600.0           9600.0      9.75       308.64
499996    28000.0      28000.0          28000.0     20.75       753.57
499998    20000.0      20000.0          20000.0     19.53       524.67
499999    25000.0      25000.0          25000.0      8.39       511.59

        annual_inc    dti  delinq_2yrs  fico_range_low  fico_range_high  ...  \
228080     55000.0  27.32          2.0           695.0            699.0  ...
92843      52000.0  20.89          0.0           710.0            714.0  ...
168585     65000.0  13.52          0.0           710.0            714.0  ...
481553     70000.0  21.96          1.0           705.0            709.0  ...
215556    185000.0  11.84          0.0           685.0            689.0  ...
...            ...    ...          ...             ...              ...  ...
499987     50000.0   2.66          0.0           670.0            674.0  ...
499988     52000.0  15.23          0.0           680.0            684.0  ...
499996    120000.0   5.21          0.0           660.0            664.0  ...
499998     65000.0  10.47          0.0           705.0            709.0  ...
499999     65000.0  27.07          0.0           720.0            724.0  ...

        addr_state_encoded  earliest_cr_line_encoded  \
228080                   9                       519
92843                    4                       151
168585                  30                       522
481553                  41                       568
215556                   5                       312
...                    ...                       ...
499987                  18                       576
499988                  41                        90
499996                  21                       513
499998                  33                       621
499999                  16                       188

        initial_list_status_encoded  last_pymnt_d_encoded  \
228080                            1                    14
92843                             1                     7
168585                            1                     8
481553                            1                    26
215556                            1                    24
...                             ...                   ...
499987                            1                    33
499988                            1                    11
499996                            1                     3
499998                            1                    20
499999                            1                     8

        next_pymnt_d_encoded  last_credit_pull_d_encoded  \
228080                     0                          11
92843                      0                          24
168585                     0                           8
481553                     0                          24
215556                     0                          27
...                      ...                         ...
499987                     0                           9
499988                     0                          24
499996                     0                          24
499998                     0                          24
499999                     0                          24

        application_type_encoded  hardship_flag_encoded  \
228080                         0                      0
92843                          0                      0
168585                         0                      0
481553                         0                      0
215556                         0                      0
...                          ...                    ...
499987                         0                      0
499988                         0                      0
499996                         0                      0
499998                         0                      0
499999                         0                      0

        disbursement_method_encoded  debt_settlement_flag_encoded
228080                            0                             0
92843                             0                             0
168585                            0                             0
481553                            0                             0
215556                            0                             0
...                             ...                           ...
499987                            0                             0
499988                            0                             0
499996                            0                             0
499998                            0                             0
499999                            0                             0

[108606 rows x 107 columns]

In [87]:
print(Y)

228080    Good
92843     Good
168585    Good
481553    Good
215556    Good
          ...
499987     Bad
499988     Bad
499996     Bad
499998     Bad
499999     Bad
Name: loan_status, Length: 108606, dtype: object

In [88]:
from sklearn.model_selection import train_test_split


X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [89]:

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
model = LogisticRegression()

In [90]:
print(X.shape, X_train.shape, X_test.shape)

(108606, 107) (86884, 107) (21722, 107)

In [92]:
#training the Logistic Regression model with training data
model.fit(X_train, Y_train)

/home/user/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [93]:
#accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [94]:
#accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [95]:
print('Accuracy on training data : ', training_data_accuracy)

Accuracy on training data :  0.9970880714515906

In [96]:
#accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [97]:
print('Accuracy on test data : ', test_data_accuracy)

Accuracy on test data :  0.9971457508516711